# -*- coding: utf-8 -*-
"""Heart Disease UCI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QyB-7nbGqO7fF3ltvvS71tYW2SPIh1JA
"""

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model.logistic import LogisticRegression
#from sklearn.cross_validation import train_test_split, cross_val_score
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

data = pd.read_csv('/content/drive/MyDrive/AI_projcet/heart.csv')

X= data.iloc[:,0:13]
Y = data.iloc[:,13]

X_train_raw, X_test_raw, y_train, y_test = train_test_split(X,Y)

vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(X_train_raw)
X_test = vectorizer.transform(X_test_raw)

classifier = LogisticRegression(penalty='l1',solver='liblinear',C=1.0,random_state=33)
classifier.fit(X,Y)
predictions = classifier.predict(X_test)
for i, prediction in enumerate(predictions[:7]):
   print(prediction,list( X_test_raw)[i])

classifier.fit(X,Y)

scores = cross_val_score(classifier, X, Y, cv=20)
print( np.mean(scores), scores)

from sklearn.metrics import make_scorer, precision_score
precision = make_scorer(precision_score)
accuracy = cross_val_score(classifier, X,Y, cv=27,scoring=precision)
print( np.mean(accuracy), accuracy)

f1s = cross_val_score(classifier, X, Y, cv=5, scoring='f1')
print( 'F1', np.mean(f1s), f1s)

recalls = cross_val_score(classifier, X, Y, cv=5, scoring='recall')
print ('Recalls', np.mean(recalls), recalls)

